export const USER_JOB_STATUS_REQUEST = "USER_JOB_STATUS_REQUEST";
export const USER_JOB_STATUS_SUCCESS = "USER_JOB_STATUS_SUCCESS";
export const USER_JOB_STATUS_FAIL = "USER_JOB_STATUS_FAIL";
export const USER_JOB_STATUS_RESET = "JOB_LOAD_SINGLE_RESET";